### ISSUE TITLE
Remove whitespace from smaller screen sizes

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#699]
**Actual Behaviour**

On smaller screen sizes, white space is being observed.

**Expected Behaviour**

No whitespace should be present.

**Screenshots of the issue**

![screenshot_20170731-091911](https://user-images.githubusercontent.com/22245418/28806035-6cfa170a-768b-11e7-9201-8f664f7bdbdd.png)

**Comment by harshit98** [comment]
@Marauderer97 @nikhilrayaprolu Any suggestions on how white space can be removed? From my side, the possible reason may be due to
- the width of menu-bar crossing screen size width.
- the width of search-bar crossing screen size width. (which will be fixed in PR: #703 )

**Comment by Marauderer97** [comment]
@harshit98 Try restricting the width of the menu bar and the search bar and try to see the results

**Comment by harshit98** [comment]
@Marauderer97 The search bar width was fixed here #680. I'm working on this to change the width of the menu to avoid white space issue.

**Comment by bhaveshAn** [comment]
Is this an active issue. Please let me know !!

**Comment by nikhilrayaprolu** [comment]
@bhaveshAn yes this is an active issue

**Comment by ValentinBercaru** [comment]
Hello, @harshit98 ! I see that this bug still exists even tough all the html elements are well organized. I think this problem can be solved by adding meta view-port tag in the index page. Can I make a Pull Request on this issue with the this issue fixed?

![screenshot_20180219-162414](https://user-images.githubusercontent.com/33882273/36382425-858543d0-1591-11e8-92c5-b92491526503.png)

**Comment by harshit98** [comment]
Yes sure @ValentinBercaru. Please go ahead. :)
